# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 09:49
from __future__ import unicode_literals

import biomedisa_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.IntegerField(default=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=biomedisa_app.models.user_directory_path, verbose_name='Image')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('imageType', models.IntegerField(choices=[(1, 'Image'), (2, 'Label')], default=1, null=True, verbose_name='Type')),
                ('final', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('log', models.IntegerField(default=0)),
                ('shortfilename', models.TextField(null=True)),
                ('job_id', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('nbrw', models.IntegerField(default=10)),
                ('sorw', models.IntegerField(default=4000)),
                ('grid', models.IntegerField(default=1)),
                ('cleanup', models.IntegerField(default=0)),
                ('allx', models.IntegerField(default=0)),
                ('hashed', models.TextField(null=True)),
                ('hashed2', models.TextField(null=True)),
                ('size', models.IntegerField(default=0)),
                ('shared', models.IntegerField(default=0)),
                ('shared_by', models.TextField(null=True)),
                ('shared_path', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
