# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='allx',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
