# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0002_auto_20170517_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='allx',
        ),
        migrations.AddField(
            model_name='upload',
            name='allxis',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
