# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0007_upload_allxis'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='friend',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
