# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0008_upload_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
