# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0009_profile_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='friendAC',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
