# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0010_upload_friendac'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='parameters',
            field=models.TextField(null=True),
        ),
    ]
