# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0011_upload_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ac_alpha',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='upload',
            name='ac_smooth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='upload',
            name='ac_steps',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='upload',
            name='allaxis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='diffusion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='smooth',
            field=models.IntegerField(default=0),
        ),
    ]
