# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0012_auto_20180207_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='active_contours',
            field=models.BooleanField(default=False),
        ),
    ]
