# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0014_auto_20180220_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='smooth',
            field=models.IntegerField(default=100),
        ),
    ]
