# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0015_auto_20180220_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='fill_wholes',
            new_name='fill_holes',
        ),
    ]
