# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0016_auto_20180309_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ignore',
            field=models.IntegerField(default=-1, verbose_name='ignore label'),
        ),
    ]
