# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0018_upload_cnn'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='cnnProject',
            field=models.TextField(null=True),
        ),
    ]
