# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0019_upload_cnnproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='cnn',
            field=models.BooleanField(default=False, verbose_name='Convolutional neural network'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='cnnProject',
            field=models.CharField(default='MyFirstProject', max_length=30, null=True, verbose_name='Project name'),
        ),
    ]
