# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0023_upload_sensitivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='sensitivity',
            field=models.IntegerField(default=100),
        ),
    ]
