# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0024_auto_20181001_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='sensitivity',
            field=models.IntegerField(default=0),
        ),
    ]
