# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0026_auto_20181004_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='cnn',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='cnnProject',
        ),
    ]
