# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0027_auto_20181005_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='compression',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='normalize',
            field=models.BooleanField(default=True),
        ),
    ]
