# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0028_auto_20181106_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='epochs',
            field=models.IntegerField(default=200, verbose_name='Epochs (AI)'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='normalize',
            field=models.BooleanField(default=True, verbose_name='Normalize (AI)'),
        ),
    ]
