# Generated by Django 2.1.5 on 2019-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0031_remove_upload_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='inverse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='inverse_steps',
            field=models.IntegerField(default=10, verbose_name='Inverse steps'),
        ),
    ]
