# Generated by Django 2.1.5 on 2019-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0032_auto_20190214_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='inverse',
            field=models.BooleanField(default=False),
        ),
    ]
