# Generated by Django 2.1.5 on 2019-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0034_auto_20190215_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='only',
            field=models.IntegerField(default=-1, verbose_name='compute only label'),
        ),
    ]
