# Generated by Django 2.1.5 on 2019-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0035_upload_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='only',
            field=models.CharField(default=-1, max_length=20, verbose_name='compute only label'),
        ),
    ]
