# Generated by Django 2.1.5 on 2019-04-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0039_auto_20190322_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='inverse_steps',
        ),
    ]
