# Generated by Django 2.1.5 on 2019-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0040_remove_upload_inverse_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='full_size',
            field=models.BooleanField(default=False, verbose_name='Full size preview'),
        ),
        migrations.AddField(
            model_name='upload',
            name='position',
            field=models.BooleanField(default=False, verbose_name='Position (AI)'),
        ),
    ]
