# Generated by Django 2.1.5 on 2019-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0041_auto_20190522_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='shift_size',
            field=models.IntegerField(default=2, verbose_name='Shift size (AI)'),
        ),
    ]
