# Generated by Django 2.2.2 on 2019-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0042_upload_shift_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='shift_size',
        ),
        migrations.AddField(
            model_name='upload',
            name='scale_size',
            field=models.IntegerField(default=256, verbose_name='Scale (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='stride_size',
            field=models.IntegerField(default=2, verbose_name='Stride size (AI)'),
        ),
    ]
