# Generated by Django 2.2.2 on 2019-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0043_auto_20190612_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='imageType',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Label'), (4, 'Network')], default=1, null=True, verbose_name='Type'),
        ),
    ]
