# Generated by Django 2.2.2 on 2019-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0044_auto_20190803_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='stride_size_prediction',
            field=models.IntegerField(default=32, verbose_name='Stride size prediction(AI)'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stride_size',
            field=models.IntegerField(default=32, verbose_name='Stride size (AI)'),
        ),
    ]
