# Generated by Django 2.2.2 on 2019-08-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0045_auto_20190819_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='stride_size_prediction',
        ),
        migrations.AddField(
            model_name='upload',
            name='stride_size_refining',
            field=models.IntegerField(default=32, verbose_name='Stride size refining (AI)'),
        ),
    ]
