# Generated by Django 2.2.2 on 2019-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0047_remove_upload_stride_size_refining'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='heart',
            field=models.BooleanField(default=False, verbose_name='Heart adaption'),
        ),
    ]
