# Generated by Django 2.2.2 on 2019-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0049_auto_20190819_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='heart',
            field=models.BooleanField(default=False, verbose_name='Human heart'),
        ),
    ]
