# Generated by Django 2.2.2 on 2019-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0050_auto_20190822_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='queue',
            field=models.IntegerField(default=1),
        ),
    ]
