# Generated by Django 3.0.3 on 2020-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0051_upload_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='scale_size',
        ),
        migrations.AddField(
            model_name='upload',
            name='balance',
            field=models.BooleanField(default=False, verbose_name='Balance training data (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='x_scale',
            field=models.IntegerField(default=256, verbose_name='X Scale (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='y_scale',
            field=models.IntegerField(default=256, verbose_name='Y Scale (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='z_scale',
            field=models.IntegerField(default=256, verbose_name='Z Scale (AI)'),
        ),
    ]
