# Generated by Django 3.0.4 on 2020-03-21 12:06

from django.db import migrations, models
#import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0053_auto_20200227_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
