# Generated by Django 3.0.4 on 2020-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0056_auto_20200322_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='status',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
