# Generated by Django 3.0.4 on 2020-03-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0058_auto_20200322_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroomspot',
            old_name='date',
            new_name='datetime',
        ),
    ]
