# Generated by Django 3.0.4 on 2020-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0059_auto_20200322_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='status_pic',
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='picture_klopapier',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='picture_mehl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='picture_nudeln',
            field=models.TextField(null=True),
        ),
    ]
