# Generated by Django 3.0.4 on 2020-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0064_auto_20200324_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='datetime',
            field=models.TextField(null=True),
        ),
    ]
