# Generated by Django 3.0.4 on 2020-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0065_auto_20200324_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='picture_desinfektionsmittel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='status_desinfektionsmittel',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
