# Generated by Django 3.0.4 on 2020-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0066_auto_20200324_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='status_klopapier',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mushroomspot',
            name='status_mehl',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mushroomspot',
            name='status_nudeln',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
