# Generated by Django 3.0.4 on 2020-03-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0068_auto_20200324_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture_desinfektionsmittel',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture_hefe',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture_klopapier',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture_mehl',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture_nudeln',
        ),
    ]
