# Generated by Django 3.0.4 on 2020-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0069_auto_20200325_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(choices=[(1, 'Desinfektion'), (2, 'Klopapier'), (3, 'Nudeln'), (4, 'Mehl'), (5, 'Hefe')], default=1)),
                ('friend', models.IntegerField(null=True)),
                ('pic', models.FileField(upload_to='goods')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='pic_desinfektionsmittel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='pic_hefe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='pic_klopapier',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='pic_mehl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='pic_nudeln',
            field=models.TextField(null=True),
        ),
    ]
