# Generated by Django 3.0.4 on 2020-03-25 10:25

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0070_auto_20200325_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroompic',
            name='friend',
        ),
        migrations.AlterField(
            model_name='mushroompic',
            name='pic',
            field=models.FileField(upload_to='', verbose_name=''),
        ),
    ]
