# Generated by Django 2.2.6 on 2020-03-26 15:58

import biomedisa_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0071_auto_20200325_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/dummy/git/biomedisa/private_storage'), upload_to=biomedisa_app.models.user_directory_path, verbose_name=''),
        ),
    ]
