# Generated by Django 2.2.6 on 2020-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0074_auto_20200326_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='heart',
        ),
        migrations.AlterField(
            model_name='upload',
            name='allaxis',
            field=models.BooleanField(default=False, verbose_name='All axes'),
        ),
    ]
