# Generated by Django 2.2.6 on 2020-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0075_auto_20200504_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='epochs',
            field=models.IntegerField(default=200, verbose_name='Number of epochs (AI)'),
        ),
    ]
