# Generated by Django 2.2.6 on 2020-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0076_auto_20200504_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='ignore',
            field=models.CharField(default='none', max_length=20, verbose_name='ignore label'),
        ),
    ]
