# Generated by Django 2.2.6 on 2020-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0077_auto_20200528_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uncertainty',
            field=models.BooleanField(default=True),
        ),
    ]
