# Generated by Django 2.2.6 on 2020-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0078_upload_uncertainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='batch_size',
            field=models.IntegerField(default=24, verbose_name='Batch size (AI)'),
        ),
    ]
