# Generated by Django 2.2.6 on 2020-09-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0079_upload_batch_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MushroomPic',
        ),
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
