# Generated by Django 3.1.2 on 2020-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0080_auto_20200908_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='flip_x',
            field=models.BooleanField(default=False, verbose_name='Flip x-axis (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='flip_y',
            field=models.BooleanField(default=False, verbose_name='Flip y-axis (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='flip_z',
            field=models.BooleanField(default=False, verbose_name='Flip z-axis (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='rotate',
            field=models.IntegerField(default=0, verbose_name='Rotate (AI)'),
        ),
    ]
