# Generated by Django 3.1.2 on 2020-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0082_auto_20201103_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='automatic_cropping',
            field=models.BooleanField(default=False, verbose_name='Automatic cropping (AI)'),
        ),
    ]
