# Generated by Django 3.1.2 on 2020-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0084_auto_20201123_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='validation_split',
            field=models.FloatField(default=0, verbose_name='Validation split (AI)'),
        ),
    ]
