# Generated by Django 3.2 on 2021-04-14 10:43

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0085_auto_20201130_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.FileField(storage=biomedisa_app.models.MyFileSystemStorage(), upload_to=biomedisa_app.models.user_directory_path, verbose_name=''),
        ),
    ]
