# Generated by Django 3.2.6 on 2022-05-18 16:06

import biomedisa_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomedisa_app', '0086_auto_20210414_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_alias', models.TextField(null=True)),
                ('repository_name', models.TextField(null=True)),
                ('repository_id', models.CharField(default=0, max_length=7)),
                ('users', models.ManyToManyField(related_name='repository', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subfamily', models.CharField(blank=True, max_length=255, null=True)),
                ('genus', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('caste', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('determined_by', models.CharField(blank=True, max_length=255, null=True)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sketchfab', models.TextField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biomedisa_app.repository')),
            ],
        ),
        migrations.CreateModel(
            name='TomographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=biomedisa_app.models.repository_directory_path, verbose_name='')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('imageType', models.IntegerField(default=1, null=True, verbose_name='Type')),
                ('shortfilename', models.TextField(null=True)),
                ('facility', models.DateField(blank=True, null=True)),
                ('technique', models.CharField(blank=True, max_length=255, null=True)),
                ('projections', models.CharField(blank=True, max_length=255, null=True)),
                ('frames_s', models.CharField(blank=True, max_length=255, null=True)),
                ('scintillator', models.DateField(blank=True, null=True)),
                ('voxel_size', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_size', models.CharField(blank=True, max_length=255, null=True)),
                ('step_scans', models.CharField(blank=True, max_length=255, null=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomedisa_app.specimen')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to=biomedisa_app.models.repository_directory_path, verbose_name='')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('imageType', models.IntegerField(default=1, null=True, verbose_name='Type')),
                ('shortfilename', models.TextField(null=True)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomedisa_app.specimen')),
            ],
        ),
    ]
