# Generated by Django 3.2.6 on 2022-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0088_auto_20220519_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='early_stopping',
            field=models.BooleanField(default=False, verbose_name='Early stopping (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='val_dice',
            field=models.BooleanField(default=False, verbose_name='Validate Dice score (AI)'),
        ),
    ]
