# Generated by Django 3.2.6 on 2022-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0089_auto_20220527_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='validation_freq',
            field=models.IntegerField(default=1, verbose_name='Validation frequency (AI)'),
        ),
    ]
