# Generated by Django 3.2.6 on 2022-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0090_upload_validation_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='val_dice',
        ),
        migrations.AddField(
            model_name='upload',
            name='val_tf',
            field=models.BooleanField(default=False, verbose_name='Validate TF accuracy (AI)'),
        ),
    ]
