# Generated by Django 3.2.6 on 2022-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0091_auto_20220531_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='compression',
            field=models.BooleanField(default=True, verbose_name='Compress results'),
        ),
    ]
