# Generated by Django 3.2.6 on 2022-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0092_auto_20220617_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform',
            field=models.CharField(default='', max_length=20),
        ),
    ]
