# Generated by Django 3.2.6 on 2023-01-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0095_auto_20230111_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='resnet',
            field=models.BooleanField(default=False, verbose_name='Use ResNet convolutional blocks (AI)'),
        ),
    ]
