# Generated by Django 3.2.6 on 2023-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0096_alter_upload_resnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='resnet',
            field=models.BooleanField(default=False, verbose_name='ResNet convolutional blocks (AI)'),
        ),
    ]
