# Generated by Django 3.2.6 on 2023-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0098_auto_20230220_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomographicdata',
            name='exposure_time_per_frame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tomographicdata',
            name='scan_tray',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tomographicdata',
            name='facility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tomographicdata',
            name='scintillator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
