# Generated by Django 3.2.6 on 2023-07-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0100_auto_20230222_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='epochs',
            field=models.IntegerField(default=100, verbose_name='Number of epochs (AI)'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='filters',
            field=models.CharField(default='32-64-128-256-512', max_length=30, verbose_name='Network architecture (AI)'),
        ),
    ]
