# Generated by Django 3.2.6 on 2023-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0102_alter_upload_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='validation_data',
            field=models.BooleanField(default=False, verbose_name='Validation data (AI)'),
        ),
    ]
