# Generated by Django 3.2.6 on 2024-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0104_alter_profile_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='header_file',
            field=models.CharField(max_length=100, null=True, verbose_name='Header file'),
        ),
    ]
