# Generated by Django 3.2.6 on 2024-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0105_upload_header_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='header_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Header file'),
        ),
    ]
