# Generated by Django 3.2.6 on 2024-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0106_alter_upload_header_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='delete_outliers',
            field=models.FloatField(default=0.1),
        ),
    ]
