# Generated by Django 3.2.6 on 2024-05-09 06:59

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0107_alter_upload_delete_outliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_size',
            field=models.IntegerField(default=biomedisa_app.models.default_storage_size),
        ),
    ]
