# Generated by Django 3.2.6 on 2024-06-20 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomedisa_app', '0108_alter_profile_storage_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='repository_alias',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repository_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repository_name',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='users',
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='biomedisa_app.repository'),
        ),
        migrations.CreateModel(
            name='RepositoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomedisa_app.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('repository', 'user')},
            },
        ),
    ]
