# Generated by Django 3.2.6 on 2024-06-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomedisa_app', '0109_auto_20240620_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(related_name='repositories', through='biomedisa_app.RepositoryUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
