# Generated by Django 3.2.6 on 2024-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0110_repository_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='scaling',
            field=models.BooleanField(default=True, verbose_name='Scale image and label data (AI)'),
        ),
    ]
