# Generated by Django 3.2.6 on 2024-09-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0112_auto_20240905_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='name_recommended',
            new_name='name',
        ),
    ]
