# Generated by Django 3.2.6 on 2024-09-05 05:19

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0114_auto_20240905_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='pic',
            field=models.FileField(default=None, upload_to=biomedisa_app.models.repository_directory_path, verbose_name=''),
        ),
    ]
