# Generated by Django 3.2.6 on 2024-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0115_specimen_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='pic',
        ),
        migrations.AddField(
            model_name='specimen',
            name='parent_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
