# Generated by Django 3.2.6 on 2024-11-18 09:59

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0116_auto_20240905_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='epochs',
            field=models.IntegerField(default=biomedisa_app.models.default_epochs, verbose_name='Number of epochs (AI)'),
        ),
    ]
