# Generated by Django 3.2.6 on 2024-11-19 16:21

import biomedisa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0117_alter_upload_epochs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_epochs',
            field=models.IntegerField(default=biomedisa_app.models.default_epochs),
        ),
        migrations.AlterField(
            model_name='upload',
            name='epochs',
            field=models.IntegerField(verbose_name='Number of epochs (AI)'),
        ),
    ]
