# Generated by Django 3.2.6 on 2026-04-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0118_auto_20241119_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
