# Generated by Django 3.2.6 on 2026-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomedisa_app', '0119_specimen_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='separation',
            field=models.BooleanField(default=False, verbose_name='Train separation model (AI)'),
        ),
        migrations.AddField(
            model_name='upload',
            name='swapaxes',
            field=models.BooleanField(default=False, verbose_name='Swap axes (AI)'),
        ),
    ]
